#Importing Libraries


In [5]:
# pip install matplotlib scikit-learn numpy

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# from google.colab import drive
# drive.mount('/content/drive')

#Import Dataset

In [8]:
dataset= pd.read_csv("phishing.csv")
dataset.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [9]:
#Analysing the data using pandas and Checking if the dataset contains any Null values.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

#Feature scaling is not required as data is already present in the same range.

#Splitting data as independent and dependent

In [10]:
#removing Index column in independent dataset
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#Splitting data into train and test

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#MODEL BUILDING -

Since the output (result) is  categorical , it comes under classification model.

Training and Testing the model -

1. LOGISTIC REGRESSION -

In [12]:
from sklearn.linear_model import LogisticRegression

logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train, y_train)

/Users/saiabhiramjaini/Desktop/ABHIRAM/MINI PROJECT/Flask API/myenv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred1 = logistic_classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score

logistic_cm = confusion_matrix(y_test, y_pred1)
print(logistic_cm)

logistic_accuracy = accuracy_score(y_test, y_pred1)
print(logistic_accuracy)

[[ 903  111]
 [  70 1127]]
0.9181365897783809


2. KNN

In [15]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [16]:
y_pred2 = knn_classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score

knn_cm = confusion_matrix(y_test, y_pred2)
print(knn_cm)

knn_accuracy = accuracy_score(y_test, y_pred2)
print(knn_accuracy)

[[544 470]
 [383 814]]
0.6142017186793306


3. Support Vector Machine(SVM)

In [18]:
from sklearn.svm import SVC

svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

SVC()

In [19]:
y_pred3 = svm_classifier.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score

svm_cm = confusion_matrix(y_test, y_pred3)
print(svm_cm)

svm_accuracy = accuracy_score(y_test, y_pred3)
print(svm_accuracy)

[[   0 1014]
 [   0 1197]]
0.5413839891451832


4.Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)

GaussianNB()

In [22]:
y_pred4 = naive_bayes_classifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score

naive_bayes_cm = confusion_matrix(y_test, y_pred4)
print(naive_bayes_cm)

naive_bayes_accuracy = accuracy_score(y_test, y_pred4)
print(naive_bayes_accuracy)

[[949  65]
 [200 997]]
0.8801447308909995


5.Decision Tree

In [24]:
from sklearn.tree import DecisionTreeClassifier

decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [25]:
y_pred5 = decision_tree_classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score

decision_tree_cm = confusion_matrix(y_test, y_pred5)
print(decision_tree_cm)

decision_tree_accuracy = accuracy_score(y_test, y_pred5)
print(decision_tree_accuracy)

[[ 949   65]
 [  49 1148]]
0.9484396200814111


6.Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier

random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [28]:
y_pred6 = random_forest_classifier.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score

random_forest_cm = confusion_matrix(y_test, y_pred6)
print(random_forest_cm)

random_forest_accuracy = accuracy_score(y_test, y_pred6)
print(random_forest_accuracy)

[[ 967   47]
 [  25 1172]]
0.9674355495251018


Model Comparision

In [30]:
final_accuracy_scores = {
    'Algorithm': ['Logistic Regression', 'K-NN', 'Support Vector Machine', 'Naive Bayes', 'Decision Tree', 'Random Forest'],
    'Accuracy': [logistic_accuracy, knn_accuracy, svm_accuracy, naive_bayes_accuracy, decision_tree_accuracy, random_forest_accuracy]
}
df = pd.DataFrame(final_accuracy_scores)
df.sort_values(by='Accuracy', ascending = False)

Algorithm  Accuracy
5           Random Forest  0.967436
4           Decision Tree  0.948440
0     Logistic Regression  0.918137
3             Naive Bayes  0.880145
1                    K-NN  0.614202
2  Support Vector Machine  0.541384

To avoid overfitting , the model which is considered here is LOGISTIC REGRESSION

ACCURACY OF DECISION TREE MODEL AND RANDOM FOREST IS HIGHEST

Even though accuracy of DECISION TREE  and RANDOM FOREST is Highest we can't build a model using that because of the following reasons:

1. Overfitting: Decision trees are prone to overfitting, especially with small datasets. Random forests mitigate this to some extent by averaging multiple trees, but they can still overfit if not properly tuned.

2. Computational Efficiency: Logistic regression is computationally less intensive compared to decision trees and random forests, making it faster to predict.

In [31]:
import pickle
pickle.dump(logistic_classifier,open('logistic_classifier_model.pkl','wb'))