#Importing Libraries


In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [70]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#Import Dataset

In [71]:
dataset= pd.read_csv("loan-train.csv")
dataset.head()

Index  UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  PrefixSuffix-  \
0      0        1        1         1        1              1             -1   
1      1        1        0         1        1              1             -1   
2      2        1        0         1        1              1             -1   
3      3        1        0        -1        1              1             -1   
4      4       -1        0        -1        1             -1             -1   

   SubDomains  HTTPS  DomainRegLen  ...  UsingPopupWindow  IframeRedirection  \
0           0      1            -1  ...                 1                  1   
1          -1     -1            -1  ...                 1                  1   
2          -1     -1             1  ...                 1                  1   
3           1      1            -1  ...                -1                  1   
4           1      1            -1  ...                 1                  1   

   AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  GoogleIndex  \
0           -1            -1               0        -1            1   
1            1            -1               1        -1            1   
2           -1            -1               1        -1            1   
3           -1            -1               0        -1            1   
4            1             1               1        -1            1   

   LinksPointingToPage  StatsReport  class  
0                    1            1     -1  
1                    0           -1     -1  
2                   -1            1     -1  
3                    1            1      1  
4                   -1           -1      1  

[5 rows x 32 columns]

In [72]:
#Analysing the data using pandas and Checking if the dataset contains any Null values.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11054 entries, 0 to 11053
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                11054 non-null  int64
 1   UsingIP              11054 non-null  int64
 2   LongURL              11054 non-null  int64
 3   ShortURL             11054 non-null  int64
 4   Symbol@              11054 non-null  int64
 5   Redirecting//        11054 non-null  int64
 6   PrefixSuffix-        11054 non-null  int64
 7   SubDomains           11054 non-null  int64
 8   HTTPS                11054 non-null  int64
 9   DomainRegLen         11054 non-null  int64
 10  Favicon              11054 non-null  int64
 11  NonStdPort           11054 non-null  int64
 12  HTTPSDomainURL       11054 non-null  int64
 13  RequestURL           11054 non-null  int64
 14  AnchorURL            11054 non-null  int64
 15  LinksInScriptTags    11054 non-null  int64
 16  ServerFormHandler    1

#Feature scaling is not required as data is already present in the same range.

#Splitting data as independent and dependent

In [73]:
#removing Index column in independent dataset
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#Splitting data into train and test

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#MODEL BUILDING -

Since the output (result) is  categorical , it comes under classification model.

Training and Testing the model -

1. LOGISTIC REGRESSION -

In [75]:
from sklearn.linear_model import LogisticRegression

logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train, y_train)

LogisticRegression()

In [76]:
y_pred1 = logistic_classifier.predict(X_test)

In [77]:
from sklearn.metrics import confusion_matrix,accuracy_score

logistic_cm = confusion_matrix(y_test, y_pred1)
print(logistic_cm)

logistic_accuracy = accuracy_score(y_test, y_pred1)
print(logistic_accuracy)

[[ 856   86]
 [  76 1193]]
0.926729986431479


2. KNN

In [78]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [79]:
y_pred2 = knn_classifier.predict(X_test)

In [80]:
from sklearn.metrics import confusion_matrix,accuracy_score

knn_cm = confusion_matrix(y_test, y_pred2)
print(knn_cm)

knn_accuracy = accuracy_score(y_test, y_pred2)
print(knn_accuracy)

[[ 876   66]
 [  43 1226]]
0.9507010402532791


3. Support Vector Machine(SVM)

In [81]:
from sklearn.svm import SVC

svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

SVC()

In [82]:
y_pred3 = svm_classifier.predict(X_test)

In [83]:
from sklearn.metrics import confusion_matrix,accuracy_score

svm_cm = confusion_matrix(y_test, y_pred3)
print(svm_cm)

svm_accuracy = accuracy_score(y_test, y_pred3)
print(svm_accuracy)

[[ 877   65]
 [  43 1226]]
0.9511533242876526


4.Naive Bayes

In [84]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)

GaussianNB()

In [85]:
y_pred4 = naive_bayes_classifier.predict(X_test)

In [86]:
from sklearn.metrics import confusion_matrix,accuracy_score

naive_bayes_cm = confusion_matrix(y_test, y_pred4)
print(naive_bayes_cm)

naive_bayes_accuracy = accuracy_score(y_test, y_pred4)
print(naive_bayes_accuracy)

[[941   1]
 [903 366]]
0.5911352329262777


5.Decision Tree

In [87]:
from sklearn.tree import DecisionTreeClassifier

decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [88]:
y_pred5 = decision_tree_classifier.predict(X_test)

In [89]:
from sklearn.metrics import confusion_matrix,accuracy_score

decision_tree_cm = confusion_matrix(y_test, y_pred5)
print(decision_tree_cm)

decision_tree_accuracy = accuracy_score(y_test, y_pred5)
print(decision_tree_accuracy)

[[ 893   49]
 [  41 1228]]
0.9592944369063772


6.Random Forest

In [90]:
from sklearn.ensemble import RandomForestClassifier

random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [91]:
y_pred6 = random_forest_classifier.predict(X_test)

In [92]:
from sklearn.metrics import confusion_matrix,accuracy_score

random_forest_cm = confusion_matrix(y_test, y_pred6)
print(random_forest_cm)

random_forest_accuracy = accuracy_score(y_test, y_pred6)
print(random_forest_accuracy)

[[ 904   38]
 [  23 1246]]
0.9724106739032112


Model Comparision

In [93]:
final_accuracy_scores = {
    'Algorithm': ['Logistic Regression', 'K-NN', 'Support Vector Machine', 'Naive Bayes', 'Decision Tree', 'Random Forest'],
    'Accuracy': [logistic_accuracy, knn_accuracy, svm_accuracy, naive_bayes_accuracy, decision_tree_accuracy, random_forest_accuracy]
}
df = pd.DataFrame(final_accuracy_scores)
df.sort_values(by='Accuracy', ascending = False)

Algorithm  Accuracy
5           Random Forest  0.972411
4           Decision Tree  0.959294
2  Support Vector Machine  0.951153
1                    K-NN  0.950701
0     Logistic Regression  0.926730
3             Naive Bayes  0.591135

To avoid overfitting , the model which is considered here is LOGISTIC REGRESSION

ACCURACY OF DECISION TREE MODEL IS HIGHEST

In [94]:
import pickle
pickle.dump(logistic_classifier,open('logistic_classifier_model.pkl','wb'))